[supabase]
url = "https://rjhnyodiiqqrlxkxkmys.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqaG55b2RpaXFxcmx4a3hrbXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1NTYwNjYsImV4cCI6MjA3MzEzMjA2Nn0.5BjpbGBi03wj1yaM8_4b15AnWiAeWItEIUpc9Xy53RA"
tabela = "PSLeads"

[whatsapp]
numero = "5511953173603"